### ISSUE TITLE
Homework 0: Rootfinding

### ISSUE THREAD

**Issue by MoeMixMC** [cucs-numcomp/numcomp-class#1]
I was wondering how to find the k value in the Newton w/ Line Search problem. Is it equal to the number of iterations or do we have to use Newton's method until we find that value?

**Comment by jedbrown** [comment]
On iteration of Newton's method, you need to find the smallest k such that the residual is reduced.  Since k is an integer, you can just check each value

* does it work with k=0?
* if no, does it work with k=1?
* ...
