### ISSUE TITLE
Class Tomorrow

### ISSUE THREAD

**Issue by noci1738** [cucs-numcomp/numcomp-class#10]
So just to be clear, a video will be released tomorrow reviewing what will be on the midterm and we will not have class in person?

**Comment by jedbrown** [comment]
Correct.On Feb 25, 2019 19:06, Noah Cisneros <notifications@github.com> wrote:So just to be clear, a video will be released tomorrow reviewing what will be on the midterm and we will not have class in person?

**Comment by margadb** [comment]
where is the video?
