### ISSUE TITLE
Difference between error and residual

### ISSUE THREAD

**Issue by tech3371** [cucs-numcomp/numcomp-class#11]
I remember doing a problem about error and residual in hw 1. I forgot how to calculate error and residual for a function. I think residual is the difference difference of actual root - estimate root, but error I am not so sure. 
And also, how do we know error is increasing while residual is decreasing?

**Comment by 1s0m0rph** [comment]
As I understand it, error is the absolute difference between the x-values (estimate of the root minus the actual location of the root) and residual is the absolute value of the function evaluated at the estimate (|f(estimate for x)|). Assuming all that's right, it should be relatively easy see when error is increasing but residual is decreasing.

**Comment by tech3371** [comment]
> As I understand it, error is the absolute difference between the x-values (estimate of the root minus the actual location of the root) and residual is the absolute value of the function evaluated at the estimate (|f(estimate for x)|). Assuming all that's right, it should be relatively easy see when error is increasing but residual is decreasing.

Thank you!
