### ISSUE TITLE
Midterm review extrapolation

### ISSUE THREAD

**Issue by tech3371** [cucs-numcomp/numcomp-class#12]
Can you give us some guidance on how to solve last part of extrapolation? We tried multiple ways and none it is giving us better accuracy(h^4). Is that because we are using left method and not the centered method?
Thank you!

**Comment by jedbrown** [comment]
Extrapolation is not the only way, but it can work for this. Try building two approximations that are each second order accurate, then combine them. Please share your code here if you're still stuck.

**Comment by tech3371** [comment]
``` 
    firstSecondOrder = (2*d2-d4)
    secondSecondOrder = 2 * d1-d2
    return firstSecondOrder + secondSecondOrder 

It gives worse error. Is that the wrong way?

**Comment by jedbrown** [comment]
Think about the last line. Why would adding those approximations be the right way to construct a more accurate approximation?

**Comment by tech3371** [comment]
Do we multiply to get h^4?

**Comment by jedbrown** [comment]
Maybe reread the extrapolation derivation in the Integration notebook.

**Comment by tech3371** [comment]
I am setting up my problem like this. Is this right way?
```
2*d2-d4 -d0 = c(h)^2
2*d1 - d2-d0 = c(2h)^2

**Comment by jedbrown** [comment]
I think your `h` and `2h` above are swapped.

**Comment by tech3371** [comment]
like this?
2*d2-d4 -d0 = c(2h)^2
2*d1 - d2-d0 = c(h)^2

**Comment by jedbrown** [comment]
How does it work?

**Comment by tech3371** [comment]
I can solve it and try. I am not sure yet. I have tried others, but they only give second order.

**Comment by tech3371** [comment]
Really bad approximation. I have spent way too much time on this problem. I think I will move on.

**Comment by jedbrown** [comment]
You're on the right track. It may be a simple typo at this point.
