### ISSUE TITLE
What should commuters do in that chance that the conditions make it too difficult to make it to the midterm tomorrow?

### ISSUE THREAD

**Issue by njalexander93** [cucs-numcomp/numcomp-class#13]
Some of us commute to Boulder from Denver, Longmont, and Fort Collins for class. I know the blizzard is supposed to pass over Boulder, which means the chances of us having class are fairly high. In the worst case scenario, where we get 10 inches in some areas and the storm continues until noon tomorrow, what should the commuters plan to do about the midterm?

**Comment by jedbrown** [comment]
We'll have a make-up if necessary. I'm hopeful that everyone will be able to safely get to campus.
