### ISSUE TITLE
Choosing a Group

### ISSUE THREAD

**Issue by njalexander93** [cucs-numcomp/numcomp-class#14]
I was unable to make it to class this week due to illness, and am a little confused about the groups... Were we assigned to specific groups in class, or can we choose any of the available groups?

**Comment by jedbrown** [comment]
We counted off forward on Tuesday and reverse today (among those who missed Tuesday). Please [join group 8](https://classroom.github.com/g/69DMGHoi), which is the next in that sequence. Thanks.

**Comment by JamesHere** [comment]
How many people are allowed in one project? I accidentally joined the group 6, which we have 4 people now. Are we good to go? Or should I quit and find another group?

**Comment by jedbrown** [comment]
The intended group size is 4.
