### ISSUE TITLE
HW 6 Question on fint_trapezoid_hierarchy

### ISSUE THREAD

**Issue by tech3371** [cucs-numcomp/numcomp-class#15]
I am confuse on the phrase 

` until the number of intervals is odd `

What interval are we talking here? Thank you in advance!

**Comment by jedbrown** [comment]
Suppose you start with 36 intervals. Then you can coarsen to 18 and then to 9, but then you can't coarsen any further. But if instead you start with 32 intervals, you can coarsen to 16, 8, 4, 2, 1.
