### ISSUE TITLE
HW gauss_quadrature

### ISSUE THREAD

**Issue by tech3371** [cucs-numcomp/numcomp-class#17]
In order to solve c or w, we need to solve f(x), but I don't see any global function f or function f passed in. How can we solve f(x)? I noticed that 
`  V, _ = vander_legendre_deriv(x) #return P,dP ` 
I understand we need to solve inv(V) to solve w, but I am confused on how to solve c. I feel like we need to use same V for both V and f(x).

**Comment by jedbrown** [comment]
The coefficient you need, `c0`, is a linear function of the vector `f(x)`, thus can be expressed as an inner product `w^T f(x)`. Your job is to compute the vector `w`.

**Comment by tech3371** [comment]
But don't we need to solve c first to get c0?

**Comment by jedbrown** [comment]
You only need the one entry. The entire vector `c` is a matrix multiplied by the vector `f(x)`.

**Comment by tech3371** [comment]
Got it! Thank you!

**Comment by 1s0m0rph** [comment]
I still don't understand this. It seems like we should substitute `V(x)c` for `f(x)` in order to solve for `w`, but I don't see how we can calculate `c`, or `c0` for that matter?

**Comment by jedbrown** [comment]
Given `f(x)`, you could compute the vector `c` by solving a linear system. Can you write the operation that computes only the entry `c0`? It can be written as an inner product `w @ f(x)` where `w` is a vector.

**Comment by 1s0m0rph** [comment]
Well, we know that `w @ f(x) = w @ V @ c` is equal to `2*c0` but I don't see how that helps us calculate `c0`. We'd still need to know `c` to evaluate that.

**Comment by jedbrown** [comment]
It looks like you're getting tangled up in what is known versus unknown. Your task here is to compute `w` such that whenever you are given an `f(x)`, the integral (`2 * c0`) can be easily computed by `2 * c0 = w @ f(x)`.

**Comment by 1s0m0rph** [comment]
If `c0` depends on `f(x)`, how do we determine `c0` without knowing `f`?

**Comment by jedbrown** [comment]
> Your task here is to compute `w`.

**Comment by 1s0m0rph** [comment]
I'm aware of that, but like you said before we need to know c0 before we can find w.

**Comment by jedbrown** [comment]
I never said that. From the definition, you already have that `c = inv(V) @ f` which is startling close to the expression `2 * c0 = w @ f`. Your task is to compute `w`. It does not depend on `f` or `c`.

**Comment by 1s0m0rph** [comment]
> You only need the one entry. The entire vector `c` is a matrix multiplied by the vector `f(x)`.

This is what made me think you did. I figured it out though.

**Comment by 1s0m0rph** [comment]
Thanks for the help, though, that last one made it clearer.
