### ISSUE TITLE
Will 1 HW still be dropped along with HW7? 

### ISSUE THREAD

**Issue by AndrewGrillot** [cucs-numcomp/numcomp-class#19]
Right now on Moodle, 1 HW automatically gets dropped. Will that go along with HW7 replacing a score too, or will HW7 end up replacing the drop?

**Comment by jedbrown** [comment]
One homework in total will be dropped. If you are happy with hw1-6, then feel free to skip hw7. If you don't like your grade in a previous homework, please complete hw7.
