### ISSUE TITLE
Homework 7 Instead of Assignment Grade Drop?

### ISSUE THREAD

**Issue by njalexander93** [cucs-numcomp/numcomp-class#20]
The grades on Moodle says that our lowest homework grade gets dropped, and Homework 7 is labled as optional on Github. Does this mean that Homework 7 just replaces one of our grades and we do not drop our lowest homework, or is a homework drop also included?

**Comment by jedbrown** [comment]
One homework in total will be dropped. That could be HW7 (e.g., you didn't submit it) or an earlier homework. Cc: #19.
