### ISSUE TITLE
Homework0 Newtonls Method

### ISSUE THREAD

**Issue by tech3371** [cucs-numcomp/numcomp-class#4]
I understand we are looking for value k that satisfy our condition. But I am confused on what k is. What is k in this method? is it the amount of iterations we have done so far?

**Comment by jedbrown** [comment]
On each step of the Newton method, `k` is the smallest integer such that the residual reduction criteria is satisfied. It may seem unintuitive at first, but it's a common way for mathematicians to explain algorithms. To implement, you could write a loop starting from `k=0` that runs within each Newton step, checking the reduction criteria until it's satisfied.

**Comment by tech3371** [comment]
Do we return k or we just exit/break when we find such k value?

**Comment by jedbrown** [comment]
You're still implementing a Newton method, so take the step that satisfies the reduction criteria.

**Comment by tech3371** [comment]
I have noticed that in newtonls() function, when it calls f(x) to find fx,dfx on first line inside for loop, it is calling f(x) I implemented for monotonic function exercise. That's why my loop goes into infinite loop and is not passing test for newtonls(). Can I do something to fix it?
