### ISSUE TITLE
Office hours

### ISSUE THREAD

**Issue by tech3371** [cucs-numcomp/numcomp-class#5]
We are at your office. Are you holding office hours today? Thank you.

**Comment by jedbrown** [comment]
Sorry, I got called out for an urgent meeting. Can you meet tomorrow? I can be available at other times.

**Comment by tech3371** [comment]
Can we meet tomorrow at 11am? I have class at your usual office hour.

**Comment by jedbrown** [comment]
Yes, or at noon.

**Comment by tech3371** [comment]
Thank you
