### ISSUE TITLE
Homework Problem 1

### ISSUE THREAD

**Issue by niharnandan** [cucs-numcomp/numcomp-class#8]
I'm trying to figure out a function which is monotonic increasing. Every function I try fails the third test.
The condition to pass the test is h[-1] > h[-2] but this can't work if the root is at 0 because the function will be getting closer to 0. Am I thinking about this wrong and is there a function that satisfies this condition because I can't think of one has a root at 0 and is absolutely increasing.

**Comment by jedbrown** [comment]
You're looking for a function where each iteration of Newton moves to a point that is further from the root.

**Comment by niharnandan** [comment]
Got it. Thanks for the tip.
