### ISSUE TITLE
QR Factorization

### ISSUE THREAD

**Issue by niharnandan** [cucs-numcomp/numcomp-class#9]
monomials(4) returns [array([1.]), array([1., 0.]), array([1., 0., 0.]), array([1., 0., 0., 0.])] as an output. How are we supposed to QR factorize this since it's not a complete matrix.

**Comment by jedbrown** [comment]
Recall that each column represents a polynomial. You have written code to compute inner products (and norms) of polynomials, and the notebook constructed projections of polynomials using those primitives. Your factor Q will also be a matrix of polynomials (represented as a list of arrays, each array representing a polynomial).
